name: Test Workflow
on:
  workflow_dispatch:
    inputs:
      filename: 
        description: Enter the file name
        required: true

jobs:
  First_Job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: create a file
        run: |
          echo "Create File"
          filename="${{ github.event.inputs.filename }}"
          echo "Hello World" > $filename
          cat $filename
          
